Repository CodeForAfrica/DebunkBot, pull requests merged in 2021-04, with the labels that each got.

#90 [Fix] Requirements and project setup
  .env.sample
  .github/workflows/production.yml
  .github/workflows/pull_request.yml
  .pre-commit-config.yaml
  Dockerfile
  Makefile
  README.md
  contrib/docker/start.sh
  debunkbot/celeryapp.py
  debunkbot/forms.py
  debunkbot/management/commands/check_replies_impact.py
  debunkbot/migrations/0001_add_tweet_model.py
  debunkbot/migrations/0002_add_claim_model.py
  debunkbot/migrations/0003_add_reply_model.py
  debunkbot/migrations/0006_gsheetclaimsdatabase.py
  debunkbot/migrations/0007_googlesheetcredentials.py
  debunkbot/migrations/0009_message_template_source.py
  debunkbot/migrations/0012_support_multiple_databases.py
  debunkbot/migrations/0015_rename_model_key_to_sheet_id.py
  debunkbot/migrations/0017_gsheetclaimsdatabase_claim_date_column_name.py
  debunkbot/models.py
  debunkbot/serializers.py
  debunkbot/settings.py
  debunkbot/test/test_claims_handler.py
  debunkbot/test/test_googlesheet_helper.py
  debunkbot/twitter/api.py
  debunkbot/twitter/process_stream.py
  debunkbot/twitter/selection/calculate_tweet_weight.py
  debunkbot/utils/gsheet/debunk_bot_gsheet_helper.py
  debunkbot/utils/gsheet/helper.py
  debunkbot/utils/links_handler.py
  debunkbot/views.py
  docker-compose.yml
  requirements-all.txt
  requirements-dev.txt
  requirements.txt
  runtime.txt
  setup.cfg
Labels: chore, dependencies

#91 Speedup tweet processing
  Dockerfile
  debunkbot/celeryapp.py
  debunkbot/management/commands/update_claims.py
  debunkbot/tasks.py
  debunkbot/utils/claims_handler.py
  debunkbot/views.py
Labels: enhancement

#92 [Chore] Official dokku action
  .github/workflows/production.yml
  .github/workflows/pull_request.yml
  Dockerfile
Labels: chore
